#!/bin/bash
source /reg/g/pcds/setup/pathmunge.sh
source /reg/g/psdm/etc/psconda.sh
cd /reg/neh/home/aegger/smalldata_tools
pythonpathmunge '/reg/neh/home/aegger/smalldata_tools'
#cd /reg/neh/operator/xcsopr/live_data/smalldata/
#pythonpathmunge '/reg/g/psdm/sw/tools/smalldata_tools'

#`which mpirun` -n 11 mpiScript.sh
`which mpirun` -n 5 mpiScript.sh
#`which mpirun` -n 23 --oversubscribe -H daq-xpp-mon05,daq-xpp-mon06 mpiScript.sh
#`which mpirun` -n 22 --oversubscribe  --hostfile xpp-monlist ./mpiScript.sh
